from jhack.utils.helpers.gather_endpoints import (
    RelationBinding,
    RelationEndpoint,
    PeerBinding,
)

SAMPLE_MATRIX = [
    [
        [
            PeerBinding(
                app="alertmanager",
                model="svcgraph",
                endpoint="replicas",
                interface="alertmanager_replica",
            )
        ],
        [],
        [
            RelationBinding(
                provider_app="alertmanager",
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
            ),
            RelationBinding(
                provider_app="alertmanager",
                provider_model="svcgraph",
                provider_endpoint="grafana-source",
                interface="grafana_datasource",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-source",
            ),
        ],
        [],
        [
            RelationBinding(
                provider_app="alertmanager",
                provider_model="svcgraph",
                provider_endpoint="alerting",
                interface="alertmanager_dispatch",
                requirer_app="loki",
                requirer_model="svcgraph",
                requirer_endpoint="alertmanager",
            )
        ],
        [],
        [
            RelationBinding(
                provider_app="alertmanager",
                provider_model="svcgraph",
                provider_endpoint="alerting",
                interface="alertmanager_dispatch",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="alertmanager",
            ),
            RelationBinding(
                provider_app="alertmanager",
                provider_model="svcgraph",
                provider_endpoint="self-metrics-endpoint",
                interface="prometheus_scrape",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
            ),
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [
            RelationBinding(
                provider_app="catalogue",
                provider_model="svcgraph",
                provider_endpoint="catalogue",
                interface="catalogue",
                requirer_app="alertmanager",
                requirer_model="svcgraph",
                requirer_endpoint="catalogue",
            )
        ],
        [
            PeerBinding(
                app="catalogue",
                model="svcgraph",
                endpoint="replicas",
                interface="catalogue_replica",
            )
        ],
        [
            RelationBinding(
                provider_app="catalogue",
                provider_model="svcgraph",
                provider_endpoint="catalogue",
                interface="catalogue",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="catalogue",
            )
        ],
        [],
        [
            RelationBinding(
                provider_app="catalogue",
                provider_model="svcgraph",
                provider_endpoint="catalogue",
                interface="catalogue",
                requirer_app="loki",
                requirer_model="svcgraph",
                requirer_endpoint="catalogue",
            )
        ],
        [],
        [
            RelationBinding(
                provider_app="catalogue",
                provider_model="svcgraph",
                provider_endpoint="catalogue",
                interface="catalogue",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="catalogue",
            )
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [],
        [],
        [
            PeerBinding(
                app="grafana",
                model="svcgraph",
                endpoint="grafana",
                interface="grafana_peers",
            ),
            PeerBinding(
                app="grafana",
                model="svcgraph",
                endpoint="replicas",
                interface="grafana_replicas",
            ),
        ],
        [],
        [],
        [],
        [
            RelationBinding(
                provider_app="grafana",
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
            )
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [],
        [],
        [],
        [],
        [],
        [],
        [
            RelationBinding(
                provider_app="istio-beacon-k8s",
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
            )
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [],
        [],
        [
            RelationBinding(
                provider_app="loki",
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
            ),
            RelationBinding(
                provider_app="loki",
                provider_model="svcgraph",
                provider_endpoint="grafana-source",
                interface="grafana_datasource",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-source",
            ),
        ],
        [],
        [
            PeerBinding(
                app="loki",
                model="svcgraph",
                endpoint="replicas",
                interface="loki_replica",
            )
        ],
        [],
        [
            RelationBinding(
                provider_app="loki",
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
            )
        ],
        [],
        [
            RelationBinding(
                provider_app="loki",
                provider_model="svcgraph",
                provider_endpoint="logging",
                interface="loki_push_api",
                requirer_app="tempo",
                requirer_model="svcgraph",
                requirer_endpoint="logging",
            )
        ],
        [
            RelationBinding(
                provider_app="loki",
                provider_model="svcgraph",
                provider_endpoint="logging",
                interface="loki_push_api",
                requirer_app="traefik",
                requirer_model="svcgraph",
                requirer_endpoint="logging",
            )
        ],
        [],
    ],
    [
        [],
        [],
        [
            RelationBinding(
                provider_app="minio",
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
            )
        ],
        [],
        [],
        [],
        [
            RelationBinding(
                provider_app="minio",
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
            )
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [],
        [],
        [
            RelationBinding(
                provider_app="prometheus",
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
            ),
            RelationBinding(
                provider_app="prometheus",
                provider_model="svcgraph",
                provider_endpoint="grafana-source",
                interface="grafana_datasource",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-source",
            ),
        ],
        [],
        [],
        [],
        [
            PeerBinding(
                app="prometheus",
                model="svcgraph",
                endpoint="prometheus-peers",
                interface="prometheus_peers",
            )
        ],
        [],
        [
            RelationBinding(
                provider_app="prometheus",
                provider_model="svcgraph",
                provider_endpoint="receive-remote-write",
                interface="prometheus_remote_write",
                requirer_app="tempo",
                requirer_model="svcgraph",
                requirer_endpoint="send-remote-write",
            )
        ],
        [],
        [],
    ],
    [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            PeerBinding(
                app="s3",
                model="svcgraph",
                endpoint="s3-integrator-peers",
                interface="s3-integrator-peers",
            )
        ],
        [
            RelationBinding(
                provider_app="s3",
                provider_model="svcgraph",
                provider_endpoint="s3-credentials",
                interface="s3",
                requirer_app="tempo",
                requirer_model="svcgraph",
                requirer_endpoint="s3",
            )
        ],
        [],
        [],
    ],
    [
        [
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_app="alertmanager",
                requirer_model="svcgraph",
                requirer_endpoint="tracing",
            )
        ],
        [
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_app="catalogue",
                requirer_model="svcgraph",
                requirer_endpoint="tracing",
            )
        ],
        [
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
            ),
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="grafana-source",
                interface="grafana_datasource",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-source",
            ),
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="tracing",
            ),
        ],
        [
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_app="istio-beacon-k8s",
                requirer_model="svcgraph",
                requirer_endpoint="charm-tracing",
            )
        ],
        [
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_app="loki",
                requirer_model="svcgraph",
                requirer_endpoint="tracing",
            )
        ],
        [],
        [
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
            ),
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="charm-tracing",
            ),
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="workload-tracing",
            ),
        ],
        [],
        [
            PeerBinding(
                app="tempo", model="svcgraph", endpoint="peers", interface="tempo_peers"
            )
        ],
        [
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_app="traefik",
                requirer_model="svcgraph",
                requirer_endpoint="charm-tracing",
            ),
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_app="traefik",
                requirer_model="svcgraph",
                requirer_endpoint="workload-tracing",
            ),
        ],
        [
            RelationBinding(
                provider_app="tempo",
                provider_model="svcgraph",
                provider_endpoint="tempo-cluster",
                interface="tempo_cluster",
                requirer_app="worker",
                requirer_model="svcgraph",
                requirer_endpoint="tempo-cluster",
            )
        ],
    ],
    [
        [
            RelationBinding(
                provider_app="traefik",
                provider_model="svcgraph",
                provider_endpoint="ingress",
                interface="ingress",
                requirer_app="alertmanager",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
            )
        ],
        [
            RelationBinding(
                provider_app="traefik",
                provider_model="svcgraph",
                provider_endpoint="ingress",
                interface="ingress",
                requirer_app="catalogue",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
            )
        ],
        [
            RelationBinding(
                provider_app="traefik",
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
            ),
            RelationBinding(
                provider_app="traefik",
                provider_model="svcgraph",
                provider_endpoint="traefik-route",
                interface="traefik_route",
                requirer_app="grafana",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
            ),
        ],
        [],
        [
            RelationBinding(
                provider_app="traefik",
                provider_model="svcgraph",
                provider_endpoint="ingress-per-unit",
                interface="ingress_per_unit",
                requirer_app="loki",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
            )
        ],
        [],
        [
            RelationBinding(
                provider_app="traefik",
                provider_model="svcgraph",
                provider_endpoint="ingress-per-unit",
                interface="ingress_per_unit",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
            ),
            RelationBinding(
                provider_app="traefik",
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_app="prometheus",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
            ),
        ],
        [],
        [
            RelationBinding(
                provider_app="traefik",
                provider_model="svcgraph",
                provider_endpoint="traefik-route",
                interface="traefik_route",
                requirer_app="tempo",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
            )
        ],
        [
            PeerBinding(
                app="traefik",
                model="svcgraph",
                endpoint="peers",
                interface="traefik_peers",
            )
        ],
        [],
    ],
    [[], [], [], [], [], [], [], [], [], [], []],
]
