from jhack.utils.helpers.gather_endpoints import PeerBinding, RelationBinding

SAMPLE_MATRIX = [
    [
        [
            PeerBinding(
                provider_endpoint="replicas",
                interface="alertmanager_replica",
            )
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-source",
                interface="grafana_datasource",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-source",
                active=True,
            ),
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="alerting",
                interface="alertmanager_dispatch",
                requirer_model="svcgraph",
                requirer_endpoint="alertmanager",
                active=True,
            )
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="alerting",
                interface="alertmanager_dispatch",
                requirer_model="svcgraph",
                requirer_endpoint="alertmanager",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="self-metrics-endpoint",
                interface="prometheus_scrape",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
                active=True,
            ),
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="catalogue",
                interface="catalogue",
                requirer_model="svcgraph",
                requirer_endpoint="catalogue",
                active=True,
            )
        ],
        [PeerBinding(provider_endpoint="replicas", interface="catalogue_replica")],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="catalogue",
                interface="catalogue",
                requirer_model="svcgraph",
                requirer_endpoint="catalogue",
                active=True,
            )
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="catalogue",
                interface="catalogue",
                requirer_model="svcgraph",
                requirer_endpoint="catalogue",
                active=True,
            )
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="catalogue",
                interface="catalogue",
                requirer_model="svcgraph",
                requirer_endpoint="catalogue",
                active=True,
            )
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [],
        [],
        [
            PeerBinding(provider_endpoint="grafana", interface="grafana_peers"),
            PeerBinding(provider_endpoint="replicas", interface="grafana_replicas"),
        ],
        [],
        [],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
                active=True,
            )
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [],
        [],
        [],
        [],
        [],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
                active=True,
            )
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-source",
                interface="grafana_datasource",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-source",
                active=True,
            ),
        ],
        [],
        [PeerBinding(provider_endpoint="replicas", interface="loki_replica")],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
                active=True,
            )
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="logging",
                interface="loki_push_api",
                requirer_model="svcgraph",
                requirer_endpoint="logging",
                active=True,
            )
        ],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="logging",
                interface="loki_push_api",
                requirer_model="svcgraph",
                requirer_endpoint="logging",
                active=True,
            )
        ],
        [],
    ],
    [
        [],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
                active=True,
            )
        ],
        [],
        [],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
                active=True,
            )
        ],
        [],
        [],
        [],
        [],
    ],
    [
        [],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-source",
                interface="grafana_datasource",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-source",
                active=True,
            ),
        ],
        [],
        [],
        [],
        [
            PeerBinding(
                provider_endpoint="prometheus-peers",
                interface="prometheus_peers",
            )
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="receive-remote-write",
                interface="prometheus_remote_write",
                requirer_model="svcgraph",
                requirer_endpoint="send-remote-write",
                active=True,
            )
        ],
        [],
        [],
    ],
    [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            PeerBinding(
                provider_endpoint="s3-integrator-peers",
                interface="s3-integrator-peers",
            )
        ],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="s3-credentials",
                interface="s3",
                requirer_model="svcgraph",
                requirer_endpoint="s3",
                active=True,
            )
        ],
        [],
        [],
    ],
    [
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_model="svcgraph",
                requirer_endpoint="tracing",
                active=True,
            )
        ],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_model="svcgraph",
                requirer_endpoint="tracing",
                active=True,
            )
        ],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-source",
                interface="grafana_datasource",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-source",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_model="svcgraph",
                requirer_endpoint="tracing",
                active=True,
            ),
        ],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_model="svcgraph",
                requirer_endpoint="charm-tracing",
                active=True,
            )
        ],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_model="svcgraph",
                requirer_endpoint="tracing",
                active=True,
            )
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_model="svcgraph",
                requirer_endpoint="charm-tracing",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_model="svcgraph",
                requirer_endpoint="workload-tracing",
                active=True,
            ),
        ],
        [],
        [PeerBinding(provider_endpoint="peers", interface="tempo_peers")],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_model="svcgraph",
                requirer_endpoint="charm-tracing",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tracing",
                interface="tracing",
                requirer_model="svcgraph",
                requirer_endpoint="workload-tracing",
                active=True,
            ),
        ],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="tempo-cluster",
                interface="tempo_cluster",
                requirer_model="svcgraph",
                requirer_endpoint="tempo-cluster",
                active=True,
            )
        ],
    ],
    [
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="ingress",
                interface="ingress",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
                active=True,
            )
        ],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="ingress",
                interface="ingress",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
                active=True,
            )
        ],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="grafana-dashboard",
                interface="grafana_dashboard",
                requirer_model="svcgraph",
                requirer_endpoint="grafana-dashboard",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="traefik-route",
                interface="traefik_route",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
                active=True,
            ),
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="ingress-per-unit",
                interface="ingress_per_unit",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
                active=True,
            )
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="ingress-per-unit",
                interface="ingress_per_unit",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
                active=True,
            ),
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="metrics-endpoint",
                interface="prometheus_scrape",
                requirer_model="svcgraph",
                requirer_endpoint="metrics-endpoint",
                active=True,
            ),
        ],
        [],
        [
            RelationBinding(
                provider_model="svcgraph",
                provider_endpoint="traefik-route",
                interface="traefik_route",
                requirer_model="svcgraph",
                requirer_endpoint="ingress",
                active=True,
            )
        ],
        [PeerBinding(provider_endpoint="peers", interface="traefik_peers")],
        [],
    ],
    [[], [], [], [], [], [], [], [], [], [], []],
]
