name: jhack
base: core20

architectures:
#  - build-on: s390x
#  - build-on: ppc64el
  - build-on: arm64
#  - build-on: armhf
  - build-on: amd64
  - build-on: i386

version: '0.3.6'
summary: Cli tool packed with juju hacks.

description: |
  An opinionated collection of scripts and utilities to make
  charming charming again. Many of the scripts in jhack interact with the juju snap and
  communicate with its client by issuing `juju` cli calls.
  This snap requires write access to ~/.local/share/juju via an interface named
  dot-local-share-juju, so that the juju client configuration can be used to talk to the
  user's clouds, controllers and models.

grade: stable
confinement: strict

parts:
  jhack:
    plugin: python
    source: https://github.com/PietroPasotti/jhack.git
    source-branch: master
    python-packages:
      - typer==0.4.1
      - ops==1.5.3
      - rich==12.0.1
      - parse==1.19.0
      - juju==2.9.7
      - asttokens
      - astunparse
      - toml
    stage-snaps:
      - juju/3.0/beta

apps:
  jhack:
    command: bin/jhack
    plugs:
      - network
      - network-bind
      - dot-local-share-juju
      - dot-jhack-config


plugs:
  # read-write access to .local/share/juju (JUJU_DATA)
  dot-local-share-juju:
    interface: personal-files
    write:
      - $HOME/.local/share/juju

  # read access to jhack configuration file
  dot-jhack-config:
    interface: personal-files
    read:
      - $HOME/.jhack

  # required to use multiprocessing semaphores
  shared-memory:
    private: true

  # read access to $HOME. Required for sync and other commands that manipulate
  #  your local code projects.
  home-read:
    interface: home
